Repository icure/icure-e2e-test-setup, pull requests merged in 2022-11, with the labels that each got.

#20 Release/0.0.25
  lib/ts/package.json
Labels: enhancement

#19 Release/0.0.25
  lib/ts/package.json
  lib/ts/src/creation.ts
  lib/ts/test/test-creation-acceptance.ts
  lib/ts/test/test-creation-kraken.ts
  lib/ts/test/test-creation-oss.ts
  lib/ts/test/utils.ts
  lib/ts/yarn.lock
Labels: enhancement

#21 Added quota option to allow creating a db with the new version of the Kraken
  lib/ts/src/index.ts
  lib/ts/test/test-groups.ts
Labels: enhancement

#24 Added Function for kraken health check
  lib/ts/src/index.ts
Labels: bug, enhancement

#27 Updated icc-api version to 6.0.3
  lib/ts/package.json
  lib/ts/yarn.lock
Labels: enhancement

#30 Added authentication header to hard delete group
  lib/ts/src/groups.ts
Labels: bug

#34 Feature/bootstrap env functions
  .idea/icure-e2e-test-setup.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  lib/kt/src/main/kotlin/com/icure/test/setup/CouchDbRestClient.kt
  lib/kt/src/main/kotlin/com/icure/test/setup/ICureTestSetup.kt
  lib/kt/src/test/kotlin/com/icure/test/setup/TestSetupTest.kt
Labels: enhancement

#35 The Master HCP user is now also an admin
  lib/ts/src/creation.ts
  lib/ts/test/test-creation-kraken.ts
  lib/ts/test/test-creation-oss.ts
Labels: enhancement
